### ISSUE TITLE
Please consider renaming the repository

### ISSUE THREAD

**Issue by unixorn** [dalailahner/zsh-theme#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but the name is awfully generic. Please consider renaming it to something descriptive, or even just name it after your github username like you did the `.zsh-theme` file

Thanks!

**Comment by dalailahner** [comment]
Yep, that's fair.
 
Renamed the repo. 👍
 
Thanks
